"""
Generates lib/globe-dots.ts: the land points the globe in the Services section
is drawn from, plus evenly spread spots on land to pin capabilities to.

Source: NASA Blue Marble specular map (ocean bright, land dark), which is
public domain and shipped with three.js examples. Only the derived coordinates
are committed, so no texture is downloaded at runtime or kept in the repo.

    python3 scripts/build-globe-dots.py path/to/earth_specular_2048.jpg
"""
import json
import math
import sys

from PIL import Image

CANDIDATES = 26000   # points tested over the whole sphere
MARKERS = 34         # spots reserved for capabilities
OCEAN_ABOVE = 150    # specular brightness above this is sea


def fibonacci_sphere(count):
    """Evenly spread directions, without the clustering you get at the poles."""
    golden = math.pi * (3 - math.sqrt(5))
    for i in range(count):
        y = 1 - (i / (count - 1)) * 2
        radius = math.sqrt(max(0.0, 1 - y * y))
        theta = golden * i
        yield math.cos(theta) * radius, y, math.sin(theta) * radius


def to_lat_lon(x, y, z):
    lat = math.degrees(math.asin(y))
    lon = math.degrees(math.atan2(z, x))
    return lat, lon


def main(path):
    mask = Image.open(path).convert("L")
    w, h = mask.size
    pixels = mask.load()

    def is_land(lat, lon):
        px = int((lon + 180) / 360 * w) % w
        py = int((90 - lat) / 180 * (h - 1))
        return pixels[px, py] < OCEAN_ABOVE

    land = []
    for x, y, z in fibonacci_sphere(CANDIDATES):
        lat, lon = to_lat_lon(x, y, z)
        # Antarctica reads as a white band and adds nothing, so leave it out.
        if lat < -60:
            continue
        if is_land(lat, lon):
            land.append((round(lat, 1), round(lon, 1)))

    # Farthest-point sampling, so capability pins spread across the continents
    # instead of bunching up wherever the land happens to be dense.
    def unit(p):
        lat, lon = map(math.radians, p)
        return math.cos(lat) * math.cos(lon), math.sin(lat), math.cos(lat) * math.sin(lon)

    chosen = [land[0]]
    vectors = [unit(land[0])]
    best = [sum(a * b for a, b in zip(unit(p), vectors[0])) for p in land]
    while len(chosen) < MARKERS:
        # The point whose closest chosen neighbour is furthest away.
        i = min(range(len(land)), key=lambda k: best[k])
        chosen.append(land[i])
        v = unit(land[i])
        vectors.append(v)
        for k, p in enumerate(land):
            best[k] = max(best[k], sum(a * b for a, b in zip(unit(p), v)))

    # Tenths of a degree keeps the file small; the globe is ~1 unit across, so
    # 0.1 degrees is far finer than a pixel.
    flat = [int(round(v * 10)) for point in land for v in point]
    spots = [[round(lat, 1), round(lon, 1)] for lat, lon in chosen]

    out = f'''// GENERATED by scripts/build-globe-dots.py. Do not edit by hand.
// Land coordinates derived from NASA's Blue Marble specular map (public domain).

/** Land points as lat/lon pairs in tenths of a degree, flattened. */
export const LAND_DOTS: number[] = {json.dumps(flat)};

/** Spots on land, spread as far apart as possible, for capability markers. */
export const MARKER_SPOTS: [number, number][] = {json.dumps(spots)};
'''
    with open("lib/globe-dots.ts", "w") as f:
        f.write(out)
    print(f"land dots: {len(land)}, markers: {len(spots)}")


if __name__ == "__main__":
    main(sys.argv[1])
